### ISSUE TITLE
getting rid of "hack" in illumina_poststats.pm

### ISSUE THREAD

**Issue by hinri** [CuppenResearch/IAP#31]
getting rid of "hack" in illumina_poststats.pm that uses the qalter -hold_jid construction
This construction is not supported by default settings in SGE
Should be solved using a hold in the qsub invocation.

Current work around:
> qconf -sconf | grep jsv
added hold_jid to  jsv_allowed_mod (qconf)

https://arc.liv.ac.uk/pipermail/gridengine-users/2009-April/024709.html

**Comment by rernst** [comment]
According to the man pages this is available to qalter: http://gridscheduler.sourceforge.net/htmlman/manuals.html and http://arc.liv.ac.uk/SGE/htmlman/manuals.html

Although I don't like the hack, we need it because the job to wait for is not present when invoking qsub. Therefor gridengine will remove the job_id from the hold_jid list.

**Comment by rernst** [comment]
@hinri Did you give this issue some more thoughts? As said I don't like the hack, but I don't know a method to avoid it... 

I have run some tests to check and we still need it:
echo "sleep 10s" | qsub -N "sleep_1"
echo "sleep 10s" | qsub -N "sleep_3"  -hold_jid sleep_1,sleep_2
echo "sleep 10s" | qsub -N "sleep_2" -hold_jid sleep_1

If sleep_1 is done, both sleep_2 and sleep_3 will start running because on submission of sleep_3 there is no job called sleep_2.

**Comment by hinri** [comment]
@Robert,

Not yet, let's include this issue when we make reconsidderations on the
pipeline regarding the use of tmpspace resources and the use of nifty
branched pipes.

Regards,

Hinri
