### ISSUE TITLE
Remove tmp dir after run?

### ISSUE THREAD

**Issue by pjotrp** [CuppenResearch/IAP#69]
After variant calling the tmp dir in the results folder is huge. Maybe add an option to remove that?

**Comment by rernst** [comment]
All tmp folders are removed if the run successfully passes all checks in the check module. Some files in the tmp folder are needed to continue if a run failes. For example if queue/gatk fails it will not redo all 'done' scatters.

**Comment by pjotrp** [comment]
Well, for people who do partial runs (like I do), I end up with a tmp dir taking up space - sometimes for days. A --cleanup option would be an idea. In fact, I would do it the other way round and give a --keep option for runs that need to be continued.

**Comment by pjotrp** [comment]
BTW, you should close an issue after a discussion is over :)

**Comment by rernst** [comment]
The check module will perfectly cleanup your partial run if you leave it on. If runs need to be continued because they failed IAP will not remove tmp if they are successful it will remove tmp. I think that it is just the behaviour you described only it is not called 'cleanup'.

Happy to reopen :). @melferink

**Comment by pjotrp** [comment]
How about renaming it to check and cleanup? So it would be clearer to people who do not read manuals :)

**Comment by rernst** [comment]
Renaming might be done in the future for now, I'll add a note to the readme, to explain what the check module does. That should be fine.
